name: icare
description: ICare Medical System.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+9

environment:
  sdk: ">=2.16.2 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.22.0
  firebase_core_platform_interface: 4.5.1
  cloud_firestore: ^3.1.15
  modal_progress_hud_nsn: ^0.2.1
  firebase_auth: ^3.3.18
  fluttertoast: ^8.0.9
  flutter_svg: ^1.0.3
  auto_size_text: ^3.0.0
  adaptive_scrollbar: ^2.1.2
  path_provider: ^2.0.10
  permission_handler: ^10.0.0
  image_picker: ^0.8.5+3
  image_cropper: ^2.0.2
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  intl: ^0.17.0
  share_plus: ^4.0.10
  fl_chart: ^0.55.0
  url_launcher: ^6.1.2
  #  pie_chart: ^5.3.0
  google_maps_flutter: ^2.2.1
  geolocator: ^9.0.0
  google_sign_in: ^5.4.2
  expandable: ^5.0.1
  printing: ^5.9.1
  syncfusion_flutter_pdfviewer: ^20.2.36-beta
  google_fonts: ^3.0.1
  dropdown_search: ^5.0.2
  flutter_file_manager: ^0.2.0
  sliding_switch: ^1.0.0
  toggle_switch: ^2.0.1
  mailer: ^5.2.0
  flutter_email_sender: ^5.1.0
  flutter_facebook_auth: ^4.4.1+1
  googleapis: ^9.2.0
  googleapis_auth: ^1.3.1
  flutter_secure_storage: ^6.0.0
  file_picker: ^5.2.0+1
  blurry_modal_progress_hud: ^1.0.3
  intl_phone_field: ^3.1.0
  cloud_functions: ^3.3.9
  firebase_messaging: ^10.0.2
  google_mobile_ads: ^2.3.0
  googledrivehandler: ^0.0.6
  multi_select_flutter: ^4.1.3


  #  extended_phone_number_input: ^1.0.2
  ##  intl_phone_number_input: ^0.7.1
  ##  intl_phone_field: ^3.1.0
  ##  intl_phone_field_improve: ^1.0.1
  #  international_phone_input: ^1.0.4
  #  libphonenumber: ^2.0.2




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  #  provider: ^6.0.2
  #  http: ^0.13.4



dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_launcher_icons: "^0.9.2"
#
#  flutter_icons:
#    android: "launcher_icon"
#      ios: true
#  image_path: "assets/img/icareicon.png"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/icareicon.png
    - assets/img/iconrounded.png
    - assets/img/icaresplash.png
    - assets/img/whitelogo.png
    - assets/img/beats.gif
    - assets/img/grmain.png
    - assets/img/graybg.png
    - assets/img/signup_login.png
    - assets/img/icaredrawer.png
    - assets/img/drawer.png
    - assets/img/allergies32.png
    - assets/img/doctors32.png
    - assets/img/labtests32.png
    - assets/img/prescriptions32.png
    - assets/img/vaccinations32.png
    - assets/img/scans32.png
    - assets/img/symptoms32.png
    - assets/img/appointments32.png
    - assets/img/settings32.png
    - assets/img/account32.png
    - assets/img/account48.png
    - assets/img/account96.png
    - assets/img/emergency32.png
    - assets/img/logout32.png
    - assets/img/analysis32.png
    - assets/img/reports32.png
    - assets/img/request1.png
    - assets/img/request2.png
    - assets/img/request3.png
    - assets/img/request4.png
    - assets/img/demo.png
    - assets/img/demo2.png
    - assets/img/vitals32.png
    - assets/img/signs32.png
    - assets/img/home32.png
    - assets/img/dependents32.png
    - assets/img/dependents48.png
    - assets/img/drive.png
    - assets/img/facebook.svg
    - assets/img/apple.svg
    - assets/img/google.svg
    - assets/svg/allergies.svg
    - assets/svg/doctors.svg
    - assets/svg/labtests.svg
    - assets/svg/prescriptions.svg
    - assets/svg/vaccinations.svg
    - assets/svg/scans.svg
    - assets/svg/symptoms.svg
    - assets/svg/appointments.svg
    - assets/svg/settings.svg
    - assets/svg/account.svg
    - assets/svg/profile.svg
    - assets/svg/emergency.svg
    - assets/svg/logout.svg
    - assets/svg/aianalysis.svg
    - assets/svg/analytics.svg
    - assets/svg/tutorial.svg
    - assets/svg/reports.svg
    - assets/svg/vitals.svg
    - assets/svg/sos.svg
    - assets/svg/home.svg
    - assets/svg/dependents.svg
    - assets/svg/facebook.svg
    - assets/svg/apple.svg
    - assets/svg/google.svg
    - assets/svg/camera.svg
    - assets/svg/gallery.svg
    - assets/svg/pdffile.svg
    - assets/files/drugsbank.txt
    - assets/files/ScansAiBank.txt
    - assets/files/SymptomsAiBank.txt
    - assets/files/Egypt.txt
    - assets/files/AllergiesAiBank.txt
    - assets/files/LabtestsAiBank.txt


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
